//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResDefProto/Res_Hero.proto
namespace Res_Table
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Skill")]
  public partial class Skill : global::ProtoBuf.IExtensible
  {
    public Skill() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResHeroInfo")]
  public partial class ResHeroInfo : global::ProtoBuf.IExtensible
  {
    public ResHeroInfo() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private byte[] _name2 = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name2
    {
      get { return _name2; }
      set { _name2 = value; }
    }
    private int _profession = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    private int _feature = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"feature", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int feature
    {
      get { return _feature; }
      set { _feature = value; }
    }
    private byte[] _des = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"des", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] des
    {
      get { return _des; }
      set { _des = value; }
    }
    private byte[] _des2 = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"des2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] des2
    {
      get { return _des2; }
      set { _des2 = value; }
    }
    private readonly global::System.Collections.Generic.List<Res_Table.Skill> _skillLst = new global::System.Collections.Generic.List<Res_Table.Skill>();
    [global::ProtoBuf.ProtoMember(8, Name=@"skillLst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Res_Table.Skill> skillLst
    {
      get { return _skillLst; }
    }
  
    private int _siphon = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"siphon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int siphon
    {
      get { return _siphon; }
      set { _siphon = value; }
    }
    private byte[] _source_name = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"source_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] source_name
    {
      get { return _source_name; }
      set { _source_name = value; }
    }
    private int _station = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"station", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int station
    {
      get { return _station; }
      set { _station = value; }
    }
    private byte[] _head_icon = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"head_icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] head_icon
    {
      get { return _head_icon; }
      set { _head_icon = value; }
    }
    private byte[] _hero_half_icon = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"hero_half_icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] hero_half_icon
    {
      get { return _hero_half_icon; }
      set { _hero_half_icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResHeroList")]
  public partial class ResHeroList : global::ProtoBuf.IExtensible
  {
    public ResHeroList() {}
    
    private readonly global::System.Collections.Generic.List<Res_Table.ResHeroInfo> _list = new global::System.Collections.Generic.List<Res_Table.ResHeroInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Res_Table.ResHeroInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}