//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResDefProto/Res_Soldier.proto
namespace Res_Table
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSoldierInfo")]
  public partial class ResSoldierInfo : global::ProtoBuf.IExtensible
  {
    public ResSoldierInfo() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private byte[] _name2 = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name2
    {
      get { return _name2; }
      set { _name2 = value; }
    }
    private int _map = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"map", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int map
    {
      get { return _map; }
      set { _map = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _desc = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private byte[] _desc2 = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"desc2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] desc2
    {
      get { return _desc2; }
      set { _desc2 = value; }
    }
    private int _image = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"image", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int image
    {
      get { return _image; }
      set { _image = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _range = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"range", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int range
    {
      get { return _range; }
      set { _range = value; }
    }
    private int _center_x = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"center_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int center_x
    {
      get { return _center_x; }
      set { _center_x = value; }
    }
    private int _center_y = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"center_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int center_y
    {
      get { return _center_y; }
      set { _center_y = value; }
    }
    private int _width = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int width
    {
      get { return _width; }
      set { _width = value; }
    }
    private int _height = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int height
    {
      get { return _height; }
      set { _height = value; }
    }
    private uint _skill_id = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private float _hp = default(float);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private float _atk = default(float);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private float _defence = default(float);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSoldierList")]
  public partial class ResSoldierList : global::ProtoBuf.IExtensible
  {
    public ResSoldierList() {}
    
    private readonly global::System.Collections.Generic.List<Res_Table.ResSoldierInfo> _list = new global::System.Collections.Generic.List<Res_Table.ResSoldierInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Res_Table.ResSoldierInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}