//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResDefProto/Res_Skill.proto
namespace Res_Table
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSkillInfo")]
  public partial class ResSkillInfo : global::ProtoBuf.IExtensible
  {
    public ResSkillInfo() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _skill_name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skill_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] skill_name
    {
      get { return _skill_name; }
      set { _skill_name = value; }
    }
    private byte[] _skill_name2 = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"skill_name2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] skill_name2
    {
      get { return _skill_name2; }
      set { _skill_name2 = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _station_type = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"station_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int station_type
    {
      get { return _station_type; }
      set { _station_type = value; }
    }
    private byte[] _desc = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private byte[] _desc2 = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"desc2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] desc2
    {
      get { return _desc2; }
      set { _desc2 = value; }
    }
    private float _skill_speed = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"skill_speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float skill_speed
    {
      get { return _skill_speed; }
      set { _skill_speed = value; }
    }
    private uint _skill_type = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"skill_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skill_type
    {
      get { return _skill_type; }
      set { _skill_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResSkillList")]
  public partial class ResSkillList : global::ProtoBuf.IExtensible
  {
    public ResSkillList() {}
    
    private readonly global::System.Collections.Generic.List<Res_Table.ResSkillInfo> _list = new global::System.Collections.Generic.List<Res_Table.ResSkillInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Res_Table.ResSkillInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}