//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CSBattle/battle.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSTeam")]
  public partial class CSTeam : global::ProtoBuf.IExtensible
  {
    public CSTeam() {}
    
    private readonly global::System.Collections.Generic.List<Pb.CSTeamPlayer> _team_player_blue = new global::System.Collections.Generic.List<Pb.CSTeamPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"team_player_blue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Pb.CSTeamPlayer> team_player_blue
    {
      get { return _team_player_blue; }
    }
  
    private readonly global::System.Collections.Generic.List<Pb.CSTeamPlayer> _team_player_red = new global::System.Collections.Generic.List<Pb.CSTeamPlayer>();
    [global::ProtoBuf.ProtoMember(2, Name=@"team_player_red", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Pb.CSTeamPlayer> team_player_red
    {
      get { return _team_player_red; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSTeamPlayer")]
  public partial class CSTeamPlayer : global::ProtoBuf.IExtensible
  {
    public CSTeamPlayer() {}
    
    private int _player_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private byte[] _player_source_name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player_source_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] player_source_name
    {
      get { return _player_source_name; }
      set { _player_source_name = value; }
    }
    private int _player_station = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_station", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int player_station
    {
      get { return _player_station; }
      set { _player_station = value; }
    }
    private readonly global::System.Collections.Generic.List<Pb.CSPlayerSkill> _player_skills = new global::System.Collections.Generic.List<Pb.CSPlayerSkill>();
    [global::ProtoBuf.ProtoMember(4, Name=@"player_skills", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Pb.CSPlayerSkill> player_skills
    {
      get { return _player_skills; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSPlayerSkill")]
  public partial class CSPlayerSkill : global::ProtoBuf.IExtensible
  {
    public CSPlayerSkill() {}
    
    private uint _skill_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroAttrCS")]
  public partial class HeroAttrCS : global::ProtoBuf.IExtensible
  {
    public HeroAttrCS() {}
    
    private int _hero_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private int _profession = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    private Pb.TeamType _team = Pb.TeamType.CS_TEAM_BLUE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Pb.TeamType.CS_TEAM_BLUE)]
    public Pb.TeamType team
    {
      get { return _team; }
      set { _team = value; }
    }
    private int _moveValue = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"moveValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moveValue
    {
      get { return _moveValue; }
      set { _moveValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"BattleSvrCmd")]
    public enum BattleSvrCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_MSGID_BATTLE_READY", Value=1)]
      CS_MSGID_BATTLE_READY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_MSGID_BATTLE_ROUND", Value=2)]
      CS_MSGID_BATTLE_ROUND = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TeamType")]
    public enum TeamType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_TEAM_BLUE", Value=1)]
      CS_TEAM_BLUE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_TEAM_RED", Value=2)]
      CS_TEAM_RED = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BattleHitState")]
    public enum BattleHitState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_BATTLE_NORMAL", Value=1)]
      CS_BATTLE_NORMAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_BATTLE_Fly", Value=2)]
      CS_BATTLE_Fly = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_BATTLE_BACK", Value=3)]
      CS_BATTLE_BACK = 3
    }
  
}