//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CSBattle/game.proto
// Note: requires additional types generated from: CSBattle/common.proto
namespace Pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccountDataCS")]
  public partial class AccountDataCS : global::ProtoBuf.IExtensible
  {
    public AccountDataCS() {}
    
    private byte[] _role_name = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"role_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] role_name
    {
      get { return _role_name; }
      set { _role_name = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _icon = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _vit = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vit
    {
      get { return _vit; }
      set { _vit = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _coin = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _cash = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cash
    {
      get { return _cash; }
      set { _cash = value; }
    }
    private int _combat_power = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"combat_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int combat_power
    {
      get { return _combat_power; }
      set { _combat_power = value; }
    }
    private readonly global::System.Collections.Generic.List<Pb.HeroDataCS> _herolist = new global::System.Collections.Generic.List<Pb.HeroDataCS>();
    [global::ProtoBuf.ProtoMember(10, Name=@"herolist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Pb.HeroDataCS> herolist
    {
      get { return _herolist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroDataCS")]
  public partial class HeroDataCS : global::ProtoBuf.IExtensible
  {
    public HeroDataCS() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _station = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"station", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int station
    {
      get { return _station; }
      set { _station = value; }
    }
    private readonly global::System.Collections.Generic.List<Pb.ArmDataCS> _armlist = new global::System.Collections.Generic.List<Pb.ArmDataCS>();
    [global::ProtoBuf.ProtoMember(4, Name=@"armlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Pb.ArmDataCS> armlist
    {
      get { return _armlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArmDataCS")]
  public partial class ArmDataCS : global::ProtoBuf.IExtensible
  {
    public ArmDataCS() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _star_count = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"star_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star_count
    {
      get { return _star_count; }
      set { _star_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}